### ISSUE TITLE
Steel Furnace is creating error of height!

### ISSUE THREAD

**Issue by MrDubstep863** [Saniee/furnacesPlus#1]
In the furnace-mk2.lua at the 136 you write `75`, it's shoud be fixed with `74`.

**Comment by Saniee** [comment]
Hello, thanks for opening the issue. Since I haven't played Factorio in the long time I didn't knew. I will fix it right away!

**Comment by Saniee** [comment]
It should be fixed.

**Comment by MrDubstep863** [comment]
k thanks
